#!/usr/bin/env python3
"""
Convert this project's MySQL dump into a PostgreSQL import script.

Usage:
  python3 migrate_mysql_dump_to_postgres.py \
    "/path/to/equipmentdb_updated.sql" \
    "/path/to/equipmentdb_postgres.sql"
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


POSTGRES_SCHEMA = """\
BEGIN;

DROP TABLE IF EXISTS changelogs;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS usertable;

CREATE TABLE changelogs (
  indexnum integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id integer NOT NULL,
  timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name varchar(255),
  type varchar(255),
  model varchar(255),
  serial varchar(30),
  description varchar(255),
  brand varchar(255),
  price integer,
  manufacturer varchar(255),
  expiration date,
  purchasedate date,
  calibrationdate date,
  calibrationmethod varchar(255),
  nextcalibration date,
  formaintenance varchar(3) DEFAULT 'No',
  location varchar(255),
  issuedby varchar(255),
  issuedto varchar(255),
  remarks varchar(255),
  status varchar(20),
  certificate text,
  modifiedby varchar(255) NOT NULL DEFAULT 'System'
);

CREATE TABLE equipment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255),
  type varchar(255),
  model varchar(255),
  serial varchar(30),
  description varchar(255),
  brand varchar(255),
  price integer,
  manufacturer varchar(255),
  expiration date,
  purchasedate date,
  calibrationdate date,
  calibrationmethod varchar(255),
  nextcalibration date,
  formaintenance varchar(3) DEFAULT 'No',
  location varchar(255),
  issuedby varchar(255),
  issuedto varchar(255),
  remarks varchar(255),
  status varchar(20),
  certificate text,
  image text
);

CREATE TABLE usertable (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(20) NOT NULL,
  password varchar(255) NOT NULL,
  role varchar(10) NOT NULL CHECK (role IN ('super', 'admin', 'basic'))
);

"""


SEQUENCE_RESETS = """\

SELECT setval(pg_get_serial_sequence('changelogs', 'indexnum'), COALESCE(MAX(indexnum), 1), MAX(indexnum) IS NOT NULL) FROM changelogs;
SELECT setval(pg_get_serial_sequence('equipment', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM equipment;
SELECT setval(pg_get_serial_sequence('usertable', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM usertable;

COMMIT;
"""


INSERT_RE = re.compile(r"^INSERT INTO `(?P<table>[^`]+)` VALUES (?P<values>.*);$")


def convert_insert(line: str) -> str | None:
    match = INSERT_RE.match(line.strip())
    if not match:
        return None

    table = match.group("table").lower()
    values = match.group("values")
    return f"INSERT INTO {table} VALUES {values};"


def convert(mysql_dump: str) -> str:
    inserts: list[str] = []

    for line in mysql_dump.splitlines():
        converted = convert_insert(line)
        if converted:
            inserts.append(converted)

    if not inserts:
        raise ValueError("No INSERT statements were found in the MySQL dump.")

    header = (
        "-- PostgreSQL migration generated from equipmentdb_updated.sql.\n"
        "-- Import with: psql \"$DATABASE_URL\" -f equipmentdb_postgres.sql\n\n"
    )
    return header + POSTGRES_SCHEMA + "\n".join(inserts) + SEQUENCE_RESETS


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    output_path.write_text(convert(input_path.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
